[webservers]
# Thêm IP của EC2 được tạo từ Terraform vào đây
# Ví dụ:
# 54.255.xxx.xxx ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/your-key.pem

[webservers:vars]
# Các biến cần thiết cho playbook
ts_key=YOUR_TAILSCALE_KEY
db_host=db-server
db_name=laravel
db_user=laravel_user
db_pass=laravel_password
ssh_private_key="YOUR_SSH_PRIVATE_KEY_FOR_GIT"
